services:
  - type: web
    name: tracker-job-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tracker-job-db
          property: connectionString
      - key: REDIS_HOST
        value: redis-13014.c325.us-east-1-4.ec2.redns.redis-cloud.com
      - key: REDIS_PORT
        value: 13014
      - key: REDIS_DB
        value: 0
      - key: REDIS_PASSWORD
        value: RkS933CNSoJjJue9CyYrehqHQKfvvidH
      - key: REDIS_USERNAME
        value: default
      - key: FLASK_ENV
        value: development

databases:
  - name: tracker-job-db
    databaseName: tracker_job_db
    user: tracker_job_user

 